In [ ]:
import numpy as np
import pandas as pd
import difflib
import re
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [ ]:
bike_data=pd.read_csv('/content/vehiclesdata.csv')
bike_data



index                name                            Model    Price  \
0        0               Honda              Amaze 1.2 VX i-VTEC   505000   
1        1       Maruti Suzuki                  Swift DZire VDI   450000   
2        2             Hyundai             i10 Magna 1.2 Kappa2   220000   
3        3              Toyota                         Glanza G   799000   
4        4              Toyota  Innova 2.4 VX 7 STR [2016-2020]  1950000   
..     ...                 ...                              ...      ...   
193    193   Bajaj Pulsar 220S                              NaN     2900   
194    194     Honda Activa 4G                              NaN     1800   
195    195         Yamaha FZ25                              NaN     1800   
196    196    Bajaj Pulsar 150                              NaN     1400   
197    197  Hero Splendor Plus                              NaN     2200   

     Year  Kilometer Fuel Type Transmission   Engine           Max Power  \
0    2017      87150    Petrol       Manual  1198 cc   87 bhp @ 6000 rpm   
1    2014      75000    Diesel       Manual  1248 cc   74 bhp @ 4000 rpm   
2    2011      67000    Petrol       Manual  1197 cc   79 bhp @ 6000 rpm   
3    2019      37500    Petrol       Manual  1197 cc   82 bhp @ 6000 rpm   
4    2018      69000    Diesel       Manual  2393 cc  148 bhp @ 3400 rpm   
..    ...        ...       ...          ...      ...                 ...   
193  2015      45000    Petrol       Manual      250                 NaN   
194  2018      25000    Petrol       Manual      350                 NaN   
195  2019       2500    Petrol       Manual      350                 NaN   
196  2015      22770    Petrol       Manual      250                 NaN   
197  2015      30000    Petrol       Manual      250                 NaN   

                 Max Torque  Seating Capacity  Fuel Tank Capacity  rating  \
0         109 Nm @ 4500 rpm                 5                  35       4   
1         190 Nm @ 2000 rpm                 5                  42       4   
2    112.7619 Nm @ 4000 rpm                 5                  35       5   
3         113 Nm @ 4200 rpm                 5                  37       3   
4         343 Nm @ 1400 rpm                 7                  55       3   
..                      ...               ...                 ...     ...   
193                     NaN                 2                  13       3   
194                     NaN                 2                  13       5   
195                     NaN                 2                  12       4   
196                     NaN                 2                  12       5   
197                     NaN                 2                  13       4   

    vehicle_type  
0            car  
1            car  
2            car  
3            car  
4            car  
..           ...  
193         bike  
194         bike  
195         bike  
196         bike  
197         bike  

[198 rows x 15 columns]

In [ ]:
#fig,ax=plt.subplots(figsize=(8,8))
#sns.distplot(bike_data.ex_showroom_price)
def clean_name(name):
   return re.sub("[^a-zA-Z0-9]","",name)
   return name


In [ ]:
# bike_data["clean_name"] = bike_data["name"].apply(clean_name)

In [ ]:
bike_data['Max Power'].fillna(bike_data['Max Power'].median,inplace=True)
bike_data['Max Torque'].fillna(bike_data['Max Torque'].median,inplace=True)
bike_data.isnull().sum()


index                  0
name                   0
Model                 99
Price                  0
Year                   0
Kilometer              0
Fuel Type              0
Transmission           0
Engine                 0
Max Power              0
Max Torque             0
Seating Capacity       0
Fuel Tank Capacity     0
rating                 0
vehicle_type           0
dtype: int64

In [ ]:
bike_data.duplicated().sum()

0

In [ ]:
selected_features = ['Price','rating','name','Kilometer','vehicle_type']
print(selected_features)

['Price', 'rating', 'name', 'Kilometer', 'vehicle_type']


In [ ]:
for feature in selected_features:
  bike_data[feature] = bike_data[feature].fillna('')

In [ ]:
combined_features=str(bike_data['Price'])+str(bike_data['rating'])+bike_data['name']+bike_data['vehicle_type']+str(bike_data['Kilometer'])

In [ ]:
print(combined_features)

0      0       505000\n1       450000\n2       220000...
1      0       505000\n1       450000\n2       220000...
2      0       505000\n1       450000\n2       220000...
3      0       505000\n1       450000\n2       220000...
4      0       505000\n1       450000\n2       220000...
                             ...                        
193    0       505000\n1       450000\n2       220000...
194    0       505000\n1       450000\n2       220000...
195    0       505000\n1       450000\n2       220000...
196    0       505000\n1       450000\n2       220000...
197    0       505000\n1       450000\n2       220000...
Length: 198, dtype: object


In [ ]:
vectorizer = TfidfVectorizer(ngram_range=(1,2))

In [ ]:
fecture_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(fecture_vectors)

  (0, 192)	0.06811669125730968
  (0, 361)	0.06811669125730968
  (0, 369)	0.06811669125730968
  (0, 99)	0.06811669125730968
  (0, 46)	0.06811669125730968
  (0, 89)	0.06811669125730968
  (0, 43)	0.06811669125730968
  (0, 91)	0.06811669125730968
  (0, 37)	0.06811669125730968
  (0, 93)	0.06811669125730968
  (0, 33)	0.06811669125730968
  (0, 117)	0.06811669125730968
  (0, 29)	0.06811669125730968
  (0, 131)	0.06811669125730968
  (0, 107)	0.06811669125730968
  (0, 129)	0.06811669125730968
  (0, 133)	0.06811669125730968
  (0, 137)	0.06811669125730968
  (0, 304)	0.26534240976932666
  (0, 200)	0.26534240976932666
  (0, 403)	0.06811669125730968
  (0, 371)	0.06811669125730968
  (0, 47)	0.06811669125730968
  (0, 42)	0.06811669125730968
  (0, 36)	0.06811669125730968
  :	:
  (197, 106)	0.057737977810748894
  (197, 128)	0.057737977810748894
  (197, 132)	0.057737977810748894
  (197, 136)	0.057737977810748894
  (197, 402)	0.057737977810748894
  (197, 271)	0.057737977810748894
  (197, 191)	0.173213933432

In [ ]:
similarity = cosine_similarity(fecture_vectors)

In [ ]:
print(similarity)

[[1.         0.78096307 0.81350311 ... 0.69618914 0.67262691 0.6685964 ]
 [0.78096307 1.         0.80544095 ... 0.68928961 0.66596089 0.66197033]
 [0.81350311 0.80544095 1.         ... 0.71800993 0.69370918 0.68955235]
 ...
 [0.69618914 0.68928961 0.71800993 ... 1.         0.5936705  0.59011312]
 [0.67262691 0.66596089 0.69370918 ... 0.5936705  1.         0.57014098]
 [0.6685964  0.66197033 0.68955235 ... 0.59011312 0.57014098 1.        ]]


In [ ]:
# getting the movie name from the users

bike_name = input('Enter bike_name: ')

Enter bike_name: Toyota


In [ ]:

#creating a list with all movie names givenin the dataset

list_of_all_name = bike_data['name'].tolist()
print(list_of_all_name)


['Honda', 'Maruti Suzuki', 'Hyundai', 'Toyota', 'Toyota', 'Maruti Suzuki', 'Mercedes-Benz', 'BMW', 'Skoda', 'Nissan', 'Hyundai', 'Renault', 'Maruti Suzuki', 'Tata', 'Volkswagen', 'Maruti Suzuki', 'Maruti Suzuki', 'Maruti Suzuki', 'Maruti Suzuki', 'Hyundai', 'Maruti Suzuki', 'Volkswagen', 'Hyundai', 'Hyundai', 'Maruti Suzuki', 'Maruti Suzuki', 'Hyundai', 'Honda', 'Hyundai', 'Honda', 'Hyundai', 'Hyundai', 'Ford', 'Honda', 'Hyundai', 'Tata', 'Tata', 'Toyota', 'Mercedes-Benz', 'Hyundai', 'Mercedes-Benz', 'Toyota', 'Audi', 'Mercedes-Benz', 'Hyundai', 'Mahindra', 'Maruti Suzuki', 'Maruti Suzuki', 'Maruti Suzuki', 'Maruti Suzuki', 'Hyundai', 'Hyundai', 'Renault', 'MG', 'Tata', 'Toyota', 'BMW', 'Jeep', 'Mahindra', 'Honda', 'BMW', 'Honda', 'Volkswagen', 'Maruti Suzuki', 'Maruti Suzuki', 'Hyundai', 'BMW', 'Toyota', 'Honda', 'Audi', 'Maruti Suzuki', 'Hyundai', 'Audi', 'Honda', 'Ford', 'Honda', 'Volkswagen', 'Honda', 'Toyota', 'Mahindra', 'Mercedes-Benz', 'Audi', 'Maruti Suzuki', 'BMW', 'Maruti Su

In [ ]:

# finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(bike_name,list_of_all_name)
print(find_close_match)

['Toyota', 'Toyota', 'Toyota']


In [ ]:
close_match = find_close_match[0]
print(close_match)

Toyota


In [ ]:
# finding the index of the bike with name

index_of_the_bike = bike_data[bike_data.name == close_match]['index'].values[0]
print(index_of_the_bike)


3


In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_bike]))
print(similarity_score)

[(0, 0.7801212005029043), (1, 0.7723898729233004), (2, 0.804572689036861), (3, 1.0000000000000007), (4, 1.0000000000000007), (5, 0.7723898729233004), (6, 0.7187639387757857), (7, 0.7606471364810309), (8, 0.704752175450625), (9, 0.7229546404883268), (10, 0.804572689036861), (11, 0.7229546404883268), (12, 0.7723898729233004), (13, 0.7457994533371004), (14, 0.753873388867914), (15, 0.7723898729233004), (16, 0.7723898729233004), (17, 0.7723898729233004), (18, 0.7723898729233004), (19, 0.804572689036861), (20, 0.7723898729233004), (21, 0.753873388867914), (22, 0.804572689036861), (23, 0.804572689036861), (24, 0.7723898729233004), (25, 0.7723898729233004), (26, 0.804572689036861), (27, 0.7801212005029043), (28, 0.804572689036861), (29, 0.7801212005029043), (30, 0.804572689036861), (31, 0.804572689036861), (32, 0.7229546404883268), (33, 0.7801212005029043), (34, 0.804572689036861), (35, 0.7457994533371004), (36, 0.7457994533371004), (37, 1.0000000000000007), (38, 0.7187639387757857), (39, 0.8

In [ ]:

len(similarity_score)

198

In [ ]:

# shorting the moving on based on their similarity score

sorted_similar_bike = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print(sorted_similar_bike)

[(3, 1.0000000000000007), (4, 1.0000000000000007), (37, 1.0000000000000007), (41, 1.0000000000000007), (55, 1.0000000000000007), (67, 1.0000000000000007), (78, 1.0000000000000007), (88, 1.0000000000000007), (2, 0.804572689036861), (10, 0.804572689036861), (19, 0.804572689036861), (22, 0.804572689036861), (23, 0.804572689036861), (26, 0.804572689036861), (28, 0.804572689036861), (30, 0.804572689036861), (31, 0.804572689036861), (34, 0.804572689036861), (39, 0.804572689036861), (44, 0.804572689036861), (50, 0.804572689036861), (51, 0.804572689036861), (65, 0.804572689036861), (71, 0.804572689036861), (85, 0.804572689036861), (97, 0.804572689036861), (98, 0.804572689036861), (0, 0.7801212005029043), (27, 0.7801212005029043), (29, 0.7801212005029043), (33, 0.7801212005029043), (59, 0.7801212005029043), (61, 0.7801212005029043), (68, 0.7801212005029043), (73, 0.7801212005029043), (75, 0.7801212005029043), (77, 0.7801212005029043), (1, 0.7723898729233004), (5, 0.7723898729233004), (12, 0.772

In [ ]:

# print the name of similar movies based on index

print('bike suggested for you: \n')
i=1
for bikes in sorted_similar_bike:
  index = bikes[0]
  name_from_index = bike_data[bike_data.index == index]['name'].values[0]
  if(i<11):
    print(i,'.', name_from_index)
    i+=1

bike suggested for you: 

1 . Toyota
2 . Toyota
3 . Toyota
4 . Toyota
5 . Toyota
6 . Toyota
7 . Toyota
8 . Toyota
9 . Hyundai
10 . Hyundai


All in one

In [ ]:
bike_name = input('Enter bike name: ')

list_of_all_name = bike_data['name'].tolist()

find_close_match = difflib.get_close_matches(bike_name,list_of_all_name)

close_match = find_close_match[0]

name_of_the_bike = bike_data[bike_data.name == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[name_of_the_bike]))

sorted_similar_bike = sorted(similarity_score,key = lambda x:x[1],reverse = True)

print('bike suggested for you: \n')
i=1
for bike in sorted_similar_bike:
  index = bike[0]
  name_from_index = bike_data[bike_data.index == index]['name'].values[0]
  if(i<11):
    print(i,'.', name_from_index)
    i+=1

Enter bike name: Bajaj Pulsar 220S
bike suggested for you: 

1 . Bajaj Pulsar 220S
2 . Bajaj Pulsar 150
3 . Bajaj Pulsar 150
4 . Bajaj Pulsar 150
5 . Bajaj Pulsar AS200
6 . Hyundai
7 . Hyundai
8 . Hyundai
9 . Hyundai
10 . Hyundai
